### ISSUE TITLE
load so failed

### ISSUE THREAD

**Issue by jackweiwang** [nicolefinnie/TFdetect#4]
i used voc weight trained yolov2 but load failed

this is java error 
`          Process: org.tensorflow.demo, PID: 26729
                                                                     java.lang.RuntimeException: Failed to load model from 'file:///android_asset/yolov2-tiny-voc.pb'
                                                                         at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:113)
                                                                         at org.tensorflow.demo.TensorFlowYoloDetector.create(TensorFlowYoloDetector.java:198)
                                                                         at org.tensorflow.demo.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:133)
                                                                         at org.tensorflow.demo.CameraActivity$5.onPreviewSizeChosen(CameraActivity.java:364)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:407)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:414)
                                                                         at org.tensorflow.demo.CameraConnectionFragment.access$000(CameraConnectionFragment.java:64)
                                                                         at org.tensorflow.demo.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:95)
                                                                         at android.view.TextureView.getHardwareLayer(TextureView.java:368)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                         at android.view.View.draw(View.java:15976)`

**Comment by jackweiwang** [comment]
tensorflow1.7.0 solved
